### ISSUE TITLE
plot_piecewise adds duplicate labels in legend

### ISSUE THREAD

**Issue by sadguitarius** [Davide-sd/sympy-plot-backends#32]
Hi @Davide-sd, thanks for the great progress on this library! I wanted to bring up a small issue. When plotting a function with plot_piecewise and adding a legend, I get a duplicate label for each individual graphical element. This doesn't seem like desired behavior. Here's a code snippet to illustrate. I'd be happy to help troubleshoot if this doesn't seem like an easy fix and you don't have the time. Thank you!

```
import spb
import sympy as sym
fn = sym.Piecewise((1, sym.Eq(a, 0)), (sym.asinh(a)/a, True))
spb.plot_piecewise(fn, legend=True, label=['piecewise function'])
```
![output](https://github.com/Davide-sd/sympy-plot-backends/assets/3022341/37c0d173-ce9a-43f4-8831-d650c553861d)

**Comment by Davide-sd** [comment]
Hello @sadguitarius ,

thank you for opening the issue. I'm going to explain how `plot_piecewise` works (which is a little bit different than other plot functions) and what you can do to achieve your desired result.

`plot_piecewise` is going to extract pieces from piecewise functions. Let's consider your example: `plot_piecewise` creates 5 different series from which it will extract numerical data:

```py
import spb
import sympy as sym
from sympy import *
sym.var("a x")
fn = sym.Piecewise((1, sym.Eq(a, 0)), (sym.asinh(a)/a, True))
p = spb.plot_piecewise(fn, legend=True)
for s in p:
    msg = str(s)
    if isinstance(s, spb.series.List2DSeries):
        msg += " " + str(s.get_data())
    print(msg)
```

Output:

```text
cartesian line: asinh(a)/a for a over (-10.0, -1e-06)
2D list plot [array([-1.e-06]), array([1.])]
cartesian line: asinh(a)/a for a over (1e-06, 10.0)
2D list plot [array([1.e-06]), array([1.])]
2D list plot [array([0.]), array([1.])]
```

Let's  zoom in around 0 in order to see all series being rendered:

```py
spb.plot_piecewise(fn, xlim=(-1e-05, 1e-05))
```
![image](https://github.com/Davide-sd/sympy-plot-backends/assets/9921777/2ebfa3e5-77e3-4b4c-a0f9-8a57dc319a4f)

The solid lines represent `sym.asinh(a)/a`. The empty circles represent the extreme values. Ideally, they should be located at `x=0`. Practically, they must be placed at some small epsilon (1e-06) away from the "breaking point", in order for the function to properly evaluate. For example: `(sym.asinh(a)/a).subs(a, 0)` gives `NaN`, which would prevent the dots from showing up on the plot. On the other hand, `(sym.asinh(a)/a).subs(a, 1e-06)` returns a numeric value.

When you execute `spb.plot_piecewise(fn, legend=True)`, you'll get this:
![image](https://github.com/Davide-sd/sympy-plot-backends/assets/9921777/b1e2fb80-46fb-404f-85e3-c58f187bac2a)
By default, each symbolic expression is assigned a default label. The legend shows two labels because the plot contains two lines. By default, there are no labels associated to points.

When you execute `spb.plot_piecewise(fn, legend=True, label=['piecewise function'])`, `plot_piecewise` sees one label, but 5 data series are present. In order to avoid raising errors, it copies the provided label to each data series. You end up with this:
![image](https://github.com/Davide-sd/sympy-plot-backends/assets/9921777/3f8f7b2e-35f1-4623-aa75-f7a2e7d55a04)

I believe you only one one entry legend for your function. You can do it in two steps. First, create a hidden plot. Then, set the labels and show it:

```py
p = spb.plot_piecewise(fn, legend=True, show=False, label="test")
for i, s in enumerate(p):
    if i != 0:
        s.label = ""
p.show()
```
![image](https://github.com/Davide-sd/sympy-plot-backends/assets/9921777/da9b89e0-f9a0-4e4b-b465-715598ea9d4b)

`plot_piecewise` definitely needs a better way to set labels. I don't have time to work on this right now, so I'll leave the issue open and fix it sometime in the future. Thanks for reporting it.

**Comment by sadguitarius** [comment]
Thanks for the detailed explanation! The workaround is totally doable. It's nice knowing what's going on under the hood, but it would be good to have a cleaner way to do this and one that conforms to expected behavior. Totally not a priority for now though! I'll check out the code if I get time too and see if I can figure anything out.

**Comment by Davide-sd** [comment]
New version is out, fixing this problem.

```py
from sympy import *
from sympy.abc import a, x
from spb import *

fn = Piecewise((1, Eq(a, 0)), (asinh(a)/a, True))
plot_piecewise(fn, legend=True, label=['piecewise function'])
```
![image](https://github.com/Davide-sd/sympy-plot-backends/assets/9921777/aebbfb1a-6292-4ed6-8ab4-61b52fc2f205)

```py
plot_piecewise(
    Heaviside(x, 0).rewrite(Piecewise),
    Piecewise(
        (sin(x), x < -5),
        (cos(x), x > 5),
        (1 / x, True)),
    ylim=(-2, 2), detect_poles=True, legend=True, label=["A", "B"])
```
![image](https://github.com/Davide-sd/sympy-plot-backends/assets/9921777/fc7b2551-6dcc-449e-afbc-3675df24b5bf)

I'm closing this issue.

**Comment by sadguitarius** [comment]
This is awesome, thanks so much!
